
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resumebuilderfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resumebuilderfrontend
  template:
    metadata:
      labels:
        app: resumebuilderfrontend
    spec:
      containers:
      - name: resume-builder-fe-k8s
        #image: flowerking21/resume_fe:v1.0
        image: ${env.DOCKER_IMAGE_RESUME_BUILDER_FRONTEND}:${env.BUILD_ID}
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
